import type { ReactNode } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../../core/card/Card";
import type { RemoteAsyncState } from "../../contracts/async-state";
import type { ChartDefinition } from "../../contracts/chart";

const palette = ["var(--primary)", "#64748b", "#0f766e", "#b45309", "#7c3aed"];
function numberValue(value: unknown) { return typeof value === "number" && Number.isFinite(value) ? value : 0; }
function pathFor(values: number[], max: number, area = false) { const line = values.map((value, index) => `${(index / Math.max(values.length - 1, 1)) * 100},${100 - (value / max) * 90}`).join(" "); return area ? `0,100 ${line} 100,100` : line; }

export function Chart<TData extends Record<string, unknown>>({ definition, state, emptyState }: { definition: Omit<ChartDefinition<TData>, "data">; state: RemoteAsyncState<TData[]>; emptyState?: ReactNode }) {
  if (state.status === "loading") return <Card><CardContent className="flex h-56 items-center justify-center text-sm text-muted-foreground">Loading chart...</CardContent></Card>;
  if (state.status === "error") return <Card><CardContent className="grid gap-2 p-6 text-sm text-destructive"><span>{state.error.message}</span>{state.onRetry && <button type="button" className="w-fit underline" onClick={state.onRetry}>Retry</button>}</CardContent></Card>;
  if (state.status === "empty" || state.data.length === 0) return <Card><CardContent className="flex h-56 items-center justify-center text-sm text-muted-foreground">{emptyState ?? "No chart data available."}</CardContent></Card>;
  const data = state.data;
  const valuesBySeries = definition.series.map((series) => data.map((row) => numberValue(row[series.key as string])));
  const max = Math.max(...valuesBySeries.flat(), 1);
  const totals = data.map((_, index) => valuesBySeries.reduce((sum, values) => sum + values[index], 0));
  const kind = definition.kind;
  const pie = kind === "pie" || kind === "donut";
  return <Card><CardHeader><CardTitle>{definition.title ?? "Chart"}</CardTitle>{definition.description && <CardDescription>{definition.description}</CardDescription>}</CardHeader><CardContent><div className="overflow-x-auto"><svg role="img" aria-label={definition.title ?? "Chart"} viewBox="0 0 100 100" preserveAspectRatio="none" className="h-56 min-w-[28rem] w-full overflow-visible">{pie ? <PieSlices values={totals} donut={kind === "donut"} /> : kind === "bar" ? <BarSeries valuesBySeries={valuesBySeries} max={max} /> : valuesBySeries.map((values, index) => <g key={String(definition.series[index].key)}><polyline fill={kind === "area" ? palette[index % palette.length] : "none"} fillOpacity={kind === "area" ? 0.16 : 1} stroke={palette[index % palette.length]} strokeWidth="1.5" vectorEffect="non-scaling-stroke" points={pathFor(values, max, kind === "area")} /><title>{definition.series[index].label}: {values.map((value) => definition.valueFormatter?.(value) ?? value).join(", ")}</title></g>)}</svg></div><div className="mt-3 flex flex-wrap gap-4 text-xs text-muted-foreground">{definition.series.map((series, index) => <span className="inline-flex items-center gap-1.5" key={String(series.key)}><i className="size-2 rounded-full" style={{ background: palette[index % palette.length] }} />{series.label}</span>)}</div>{definition.accessibleDataTable !== false && <div className="mt-3 overflow-auto"><table className="w-full text-left text-xs"><caption className="sr-only">Chart data</caption><thead><tr><th className="p-1">Index</th>{definition.series.map((series) => <th className="p-1" key={String(series.key)}>{series.label}</th>)}</tr></thead><tbody>{data.map((row, rowIndex) => <tr key={rowIndex}><td className="p-1">{rowIndex + 1}</td>{definition.series.map((series) => <td className="p-1" key={String(series.key)}>{definition.valueFormatter?.(numberValue(row[series.key as string])) ?? numberValue(row[series.key as string])}</td>)}</tr>)}</tbody></table></div>}</CardContent></Card>;
}

function BarSeries({ valuesBySeries, max }: { valuesBySeries: number[][]; max: number }) { const count = valuesBySeries[0]?.length ?? 0; return <>{Array.from({ length: count }, (_, column) => valuesBySeries.map((values, seriesIndex) => { const width = 80 / Math.max(count * valuesBySeries.length, 1); const x = 10 + (column * valuesBySeries.length + seriesIndex) * width; const height = (values[column] / max) * 90; return <rect key={`${column}-${seriesIndex}`} x={x} y={100 - height} width={Math.max(width - 0.8, 1)} height={height} fill={palette[seriesIndex % palette.length]} rx="0.5"><title>{values[column]}</title></rect>; }))}</>; }
function PieSlices({ values, donut }: { values: number[]; donut: boolean }) { const total = values.reduce((sum, value) => sum + value, 0) || 1; let cursor = -Math.PI / 2; return <>{values.map((value, index) => { const start = cursor; const end = cursor + (value / total) * Math.PI * 2; cursor = end; const large = end - start > Math.PI ? 1 : 0; const x1 = 50 + 40 * Math.cos(start); const y1 = 50 + 40 * Math.sin(start); const x2 = 50 + 40 * Math.cos(end); const y2 = 50 + 40 * Math.sin(end); const path = `M 50 50 L ${x1} ${y1} A 40 40 0 ${large} 1 ${x2} ${y2} Z`; return <path key={index} d={path} fill={palette[index % palette.length]} stroke="var(--background)" strokeWidth="0.8"><title>{value}</title></path>; })}{donut && <circle cx="50" cy="50" r="20" fill="var(--background)" />}</>; }
