import { useMemo, useState, type ChangeEvent, type ReactNode, type RefObject } from "react";
import { cn } from "../../lib/cn";

export function Command({ children, className }: { children: ReactNode; className?: string }) { return <div role="search" className={cn("flex w-full flex-col overflow-hidden rounded-lg border bg-background", className)}>{children}</div>; }
export function CommandInput({ value, defaultValue = "", onValueChange, placeholder = "Type a command...", inputRef }: { value?: string; defaultValue?: string; onValueChange?: (value: string) => void; placeholder?: string; inputRef?: RefObject<HTMLInputElement | null> }) { const [internalValue, setInternalValue] = useState(defaultValue); const currentValue = value ?? internalValue; const handleChange = (event: ChangeEvent<HTMLInputElement>) => { if (value === undefined) setInternalValue(event.target.value); onValueChange?.(event.target.value); }; return <input ref={inputRef} autoFocus value={currentValue} onChange={handleChange} placeholder={placeholder} className="h-10 border-b bg-transparent px-3 text-sm outline-none" />; }
export function CommandList({ children }: { children: ReactNode }) { return <div role="listbox" className="max-h-64 overflow-y-auto p-1">{children}</div>; }
export function CommandEmpty({ children = "No results found." }: { children?: ReactNode }) { return <div className="py-6 text-center text-sm text-muted-foreground">{children}</div>; }
export function CommandGroup({ heading, children }: { heading?: ReactNode; children: ReactNode }) { return <div className="p-1"><div className="px-2 py-1.5 text-xs font-medium text-muted-foreground">{heading}</div>{children}</div>; }
export function CommandItem({ children, onSelect, value, query = "", active = false, className }: { children: ReactNode; onSelect?: () => void; value: string; query?: string; active?: boolean; className?: string }) { const visible = useMemo(() => !query || value.toLowerCase().includes(query.toLowerCase()), [query, value]); if (!visible) return null; return <button type="button" role="option" aria-selected={active} className={cn("flex w-full items-center rounded-md px-2 py-2 text-left text-sm hover:bg-muted", active && "bg-muted", className)} onClick={onSelect}>{children}</button>; }
export function useCommandQuery(defaultValue = "") { return useState(defaultValue); }
