import type { ReactNode } from "react";

export type ComponentVariant = {
  name: string;
  description: string;
  code: string;
  preview?: ReactNode;
};

export type ComponentDoc = {
  path: string;
  category: string;
  group: "Core primitives" | "Forms & controls" | "Data display" | "Overlays & menus" | "Navigation" | "Calendar & dates" | "Charts & visualization" | "Files & uploads" | "Patterns";
  name: string;
  description: string;
  module: string;
  usage: string;
  api: { name: string; type: string; description: string }[];
  variants: ComponentVariant[];
};

const core = "edjavu_ui/core";
const composites = "edjavu_ui/composites";
const shell = "edjavu_ui/shell";

const doc = (value: ComponentDoc): ComponentDoc => value;

export const componentRegistry: ComponentDoc[] = [
  doc({ path: "/components/core/button", category: "Core primitives", group: "Core primitives", name: "Button", description: "Triggers an action or submits a user decision.", module: core, usage: '<Button variant="outline" size="sm">Cancel</Button>', api: [{ name: "variant", type: '"default" | "primary" | "secondary" | "outline" | "ghost" | "destructive" | "link" | "danger"', description: "Controls the visual treatment." }, { name: "size", type: '"default" | "xs" | "sm" | "lg" | "icon" | "icon-sm" | "icon-lg"', description: "Controls the button dimensions." }, { name: "disabled", type: "boolean", description: "Prevents interaction and applies the disabled state." }], variants: [{ name: "Default", description: "Primary action treatment.", code: '<Button>Default</Button>' }, { name: "Secondary", description: "Lower emphasis action.", code: '<Button variant="secondary">Secondary</Button>' }, { name: "Outline", description: "Bordered action for secondary surfaces.", code: '<Button variant="outline">Outline</Button>' }, { name: "Ghost", description: "Minimal action for toolbars and compact controls.", code: '<Button variant="ghost">Ghost</Button>' }, { name: "Destructive", description: "Action that can remove or invalidate data.", code: '<Button variant="destructive">Delete</Button>' }, { name: "Link", description: "Text-like action treatment.", code: '<Button variant="link">View details</Button>' }, { name: "Sizes", description: "Use the size contract for compact or prominent actions.", code: '<Button size="xs">XS</Button>\n<Button size="sm">Small</Button>\n<Button size="lg">Large</Button>' }] }),
  doc({ path: "/components/core/card", category: "Core primitives", group: "Core primitives", name: "Card", description: "Groups related content into a readable surface.", module: core, usage: "<Card><CardHeader><CardTitle>Title</CardTitle></CardHeader><CardContent>Content</CardContent></Card>", api: [{ name: "CardHeader", type: "ReactNode", description: "Heading and supporting context." }, { name: "CardContent", type: "ReactNode", description: "Main content area." }, { name: "CardFooter", type: "ReactNode", description: "Actions or supporting controls." }], variants: [{ name: "Content card", description: "A simple content surface.", code: "<Card><CardContent>Content</CardContent></Card>" }, { name: "Structured card", description: "Header, content, and footer composition.", code: "<Card><CardHeader>...</CardHeader><CardContent>...</CardContent><CardFooter>...</CardFooter></Card>" }] }),
  doc({ path: "/components/core/badge", category: "Core primitives", group: "Core primitives", name: "Badge", description: "Labels a status, category, or short piece of metadata.", module: core, usage: '<Badge variant="secondary">Stable</Badge>', api: [{ name: "variant", type: '"default" | "secondary" | "destructive" | "outline" | "ghost" | "link"', description: "Controls the badge treatment." }], variants: [{ name: "Default", description: "Primary status label.", code: '<Badge>Stable</Badge>' }, { name: "Secondary", description: "Muted status label.", code: '<Badge variant="secondary">Preview</Badge>' }, { name: "Destructive", description: "Error or risky status.", code: '<Badge variant="destructive">Deprecated</Badge>' }, { name: "Outline", description: "Low emphasis label.", code: '<Badge variant="outline">Optional</Badge>' }] }),
  doc({ path: "/components/core/input", category: "Core primitives", group: "Forms & controls", name: "Input", description: "Accepts a short, single-line value from the user.", module: core, usage: '<Input placeholder="Component name" />', api: [{ name: "value", type: "string", description: "Controlled input value." }, { name: "placeholder", type: "string", description: "Guidance shown before a value is entered." }, { name: "disabled", type: "boolean", description: "Prevents editing." }], variants: [{ name: "Default", description: "Single-line text input.", code: '<Input placeholder="Component name" />' }, { name: "Disabled", description: "Unavailable input state.", code: '<Input disabled placeholder="Unavailable" />' }] }),
  doc({ path: "/components/core/label", category: "Core primitives", group: "Forms & controls", name: "Label", description: "Associates visible text with a form control.", module: core, usage: '<Label htmlFor="email">Email</Label>', api: [{ name: "htmlFor", type: "string", description: "ID of the associated form control." }], variants: [{ name: "Default", description: "Text label for a control.", code: '<Label htmlFor="email">Email</Label>' }] }),
  doc({ path: "/components/core/textarea", category: "Core primitives", group: "Forms & controls", name: "Textarea", description: "Accepts multiline text input.", module: core, usage: '<Textarea placeholder="Describe the change" />', api: [{ name: "value", type: "string", description: "Controlled text value." }, { name: "rows", type: "number", description: "Suggested visible row count." }], variants: [{ name: "Default", description: "Multiline text input.", code: '<Textarea placeholder="Describe the change" />' }] }),
  doc({ path: "/components/core/checkbox", category: "Core primitives", group: "Forms & controls", name: "Checkbox", description: "Represents an independent boolean choice.", module: core, usage: '<Checkbox checked={checked} onCheckedChange={setChecked} />', api: [{ name: "checked", type: "boolean", description: "Controlled checked state." }, { name: "onCheckedChange", type: "(checked) => void", description: "Called when the state changes." }], variants: [{ name: "Unchecked", description: "Default boolean control.", code: '<Checkbox />' }, { name: "Checked", description: "Selected boolean control.", code: '<Checkbox checked />' }] }),
  doc({ path: "/components/core/switch", category: "Core primitives", group: "Forms & controls", name: "Switch", description: "Toggles a setting between two states.", module: core, usage: '<Switch checked={enabled} onCheckedChange={setEnabled} />', api: [{ name: "checked", type: "boolean", description: "Controlled on/off state." }, { name: "onCheckedChange", type: "(checked) => void", description: "Called when the state changes." }], variants: [{ name: "Off", description: "Inactive setting.", code: '<Switch checked={false} />' }, { name: "On", description: "Active setting.", code: '<Switch checked />' }] }),
  doc({ path: "/components/core/select", category: "Core primitives", group: "Forms & controls", name: "Select", description: "Displays a native list of options.", module: core, usage: '<Select defaultValue="stable"><option value="stable">Stable</option></Select>', api: [{ name: "value", type: "string", description: "Controlled selected value." }, { name: "onChange", type: "ChangeEventHandler<HTMLSelectElement>", description: "Called when an option is selected." }, { name: "disabled", type: "boolean", description: "Prevents selection." }], variants: [{ name: "Default", description: "Native select with options.", code: '<Select><option>Stable</option></Select>' }, { name: "Disabled", description: "Unavailable select state.", code: '<Select disabled><option>Unavailable</option></Select>' }] }),
  doc({ path: "/components/core/tabs", category: "Core primitives", group: "Navigation", name: "Tabs", description: "Switches between related panels without changing the route.", module: core, usage: '<Tabs defaultValue="preview">...</Tabs>', api: [{ name: "defaultValue", type: "string", description: "Initially selected tab." }, { name: "value", type: "string", description: "Controlled selected tab." }, { name: "onValueChange", type: "(value) => void", description: "Called when the tab changes." }], variants: [{ name: "Default", description: "Tab list with content panels.", code: '<Tabs defaultValue="preview">...</Tabs>' }] }),
  doc({ path: "/components/core/alert", category: "Core primitives", group: "Core primitives", name: "Alert", description: "Communicates an important message in context.", module: core, usage: '<Alert><AlertDescription>Saved.</AlertDescription></Alert>', api: [{ name: "children", type: "ReactNode", description: "Alert content." }], variants: [{ name: "Default", description: "Informational inline message.", code: '<Alert><AlertDescription>Saved.</AlertDescription></Alert>' }] }),
  doc({ path: "/components/core/avatar", category: "Core primitives", group: "Core primitives", name: "Avatar", description: "Represents a user or entity with an image and fallback.", module: core, usage: '<Avatar><AvatarFallback>GP</AvatarFallback></Avatar>', api: [{ name: "AvatarImage", type: "src, alt", description: "Optional image content." }, { name: "AvatarFallback", type: "children", description: "Fallback when no image is available." }], variants: [{ name: "Fallback", description: "Initials or label fallback.", code: '<Avatar><AvatarFallback>GP</AvatarFallback></Avatar>' }, { name: "Image", description: "Image with fallback content.", code: '<Avatar><AvatarImage src={src} /><AvatarFallback>GP</AvatarFallback></Avatar>' }] }),
  doc({ path: "/components/core/progress", category: "Core primitives", group: "Data display", name: "Progress", description: "Communicates completion of a known task.", module: core, usage: '<Progress value={64} />', api: [{ name: "value", type: "number", description: "Completion percentage." }], variants: [{ name: "Determinate", description: "Progress with a known value.", code: '<Progress value={64} />' }] }),
  doc({ path: "/components/core/skeleton", category: "Core primitives", group: "Data display", name: "Skeleton", description: "Reserves space while content is loading.", module: core, usage: '<Skeleton className="h-4 w-32" />', api: [{ name: "className", type: "string", description: "Controls the shape and dimensions." }], variants: [{ name: "Line", description: "Placeholder for text.", code: '<Skeleton className="h-4 w-32" />' }, { name: "Block", description: "Placeholder for a larger surface.", code: '<Skeleton className="h-24 w-full" />' }] }),
  doc({ path: "/components/core/table", category: "Core primitives", group: "Data display", name: "Table", description: "Presents structured data for scanning and comparison.", module: core, usage: '<Table><TableHeader>...</TableHeader><TableBody>...</TableBody></Table>', api: [{ name: "TableHeader", type: "ReactNode", description: "Column headings." }, { name: "TableBody", type: "ReactNode", description: "Data rows." }, { name: "TableFooter", type: "ReactNode", description: "Summary or actions." }], variants: [{ name: "Basic", description: "Header and body composition.", code: '<Table>...</Table>' }, { name: "With footer", description: "Table with summary content.", code: '<Table>...<TableFooter>...</TableFooter></Table>' }] }),
  doc({ path: "/components/core/separator", category: "Core primitives", group: "Core primitives", name: "Separator", description: "Separates related regions of content.", module: core, usage: '<Separator />', api: [{ name: "orientation", type: '"horizontal" | "vertical"', description: "Direction of the separator." }], variants: [{ name: "Horizontal", description: "Separates stacked content.", code: '<Separator />' }, { name: "Vertical", description: "Separates inline content.", code: '<Separator orientation="vertical" />' }] }),
  doc({ path: "/components/core/accordion", category: "Core primitives", group: "Core primitives", name: "Accordion", description: "Reveals and hides related sections of content.", module: core, usage: '<Accordion><AccordionItem>...</AccordionItem></Accordion>', api: [{ name: "AccordionItem", type: "ReactNode", description: "Collapsible section." }, { name: "AccordionTrigger", type: "ReactNode", description: "Section control." }, { name: "AccordionContent", type: "ReactNode", description: "Expanded content." }], variants: [{ name: "Single section", description: "One expandable section.", code: '<Accordion>...</Accordion>' }] }),
  doc({ path: "/components/core/tooltip", category: "Core primitives", group: "Overlays & menus", name: "Tooltip", description: "Provides short contextual information on focus or hover.", module: core, usage: '<Tooltip content="Copy"><Button size="icon">...</Button></Tooltip>', api: [{ name: "content", type: "ReactNode", description: "Context shown near the trigger." }], variants: [{ name: "Default", description: "Tooltip around a control.", code: '<Tooltip content="Copy">...</Tooltip>' }] }),
  doc({ path: "/components/core/popover", category: "Core primitives", group: "Overlays & menus", name: "Popover", description: "Anchors interactive content to a trigger.", module: core, usage: '<Popover trigger={<Button>Open</Button>}>Content</Popover>', api: [{ name: "trigger", type: "ReactNode", description: "Element that opens the popover." }, { name: "children", type: "ReactNode", description: "Interactive popover content." }], variants: [{ name: "Default", description: "Popover with consumer content.", code: '<Popover trigger={<Button>Open</Button>}>Content</Popover>' }] }),
  doc({ path: "/components/core/slider", category: "Core primitives", group: "Forms & controls", name: "Slider", description: "Selects a numeric value within a range.", module: core, usage: '<Slider value={[64]} onValueChange={setValue} />', api: [{ name: "value", type: "number[]", description: "Controlled slider value." }, { name: "min / max", type: "number", description: "Range boundaries." }, { name: "step", type: "number", description: "Increment between values." }], variants: [{ name: "Default", description: "Single value slider.", code: '<Slider defaultValue={[64]} />' }] }),
  doc({ path: "/components/core/command", category: "Core primitives", group: "Overlays & menus", name: "Command", description: "Provides searchable command and option navigation.", module: core, usage: '<Command><CommandInput /><CommandList>...</CommandList></Command>', api: [{ name: "CommandInput", type: "ReactNode", description: "Search field." }, { name: "CommandList", type: "ReactNode", description: "Filtered result list." }, { name: "CommandItem", type: "ReactNode", description: "Selectable command." }], variants: [{ name: "Search list", description: "Command input with grouped results.", code: '<Command>...</Command>' }] }),
  doc({ path: "/components/core/button-group", category: "Core primitives", group: "Forms & controls", name: "Button Group", description: "Groups related actions into one control surface.", module: core, usage: '<ButtonGroup><Button>One</Button><Button>Two</Button></ButtonGroup>', api: [{ name: "children", type: "ReactNode", description: "Buttons or controls in the group." }], variants: [{ name: "Horizontal", description: "Adjacent actions.", code: '<ButtonGroup>...</ButtonGroup>' }] }),
  doc({ path: "/components/core/toggle-group", category: "Core primitives", group: "Forms & controls", name: "Toggle Group", description: "Coordinates one or more toggle choices.", module: core, usage: '<ToggleGroup type="single">...</ToggleGroup>', api: [{ name: "type", type: '"single" | "multiple"', description: "Selection model." }, { name: "value", type: "string | string[]", description: "Controlled selection." }], variants: [{ name: "Single", description: "One active option.", code: '<ToggleGroup type="single">...</ToggleGroup>' }, { name: "Multiple", description: "Several active options.", code: '<ToggleGroup type="multiple">...</ToggleGroup>' }] }),
  doc({ path: "/components/core/overlay", category: "Core primitives", group: "Overlays & menus", name: "Overlay", description: "Provides dialog, drawer, and sheet surfaces.", module: core, usage: '<Dialog open={open} onOpenChange={setOpen}>Content</Dialog>', api: [{ name: "open", type: "boolean", description: "Controlled visibility." }, { name: "onOpenChange", type: "(open) => void", description: "Called when visibility changes." }], variants: [{ name: "Dialog", description: "Centered modal surface.", code: '<Dialog>Content</Dialog>' }, { name: "Drawer", description: "Edge-attached surface.", code: '<Drawer>Content</Drawer>' }, { name: "Sheet", description: "Side panel surface.", code: '<Sheet>Content</Sheet>' }] }),
  doc({ path: "/components/navigation/sidebar", category: "Core primitives", group: "Navigation", name: "Sidebar", description: "Provides collapsible navigation structure for a consumer shell.", module: shell, usage: '<SidebarProvider><Sidebar>...</Sidebar></SidebarProvider>', api: [{ name: "open", type: "boolean", description: "Controlled expanded state." }, { name: "onOpenChange", type: "(open) => void", description: "Called when the state changes." }], variants: [{ name: "Expanded", description: "Full navigation labels.", code: '<Sidebar>...</Sidebar>' }, { name: "Collapsed", description: "Icon-focused navigation.", code: '<Sidebar collapsible="icon">...</Sidebar>' }] }),
  doc({ path: "/components/navigation/breadcrumb", category: "Core primitives", group: "Navigation", name: "Breadcrumb", description: "Shows the current location within a hierarchy.", module: shell, usage: '<Breadcrumb items={items} />', api: [{ name: "items", type: "BreadcrumbItem[]", description: "Consumer-owned path labels and links." }], variants: [{ name: "Default", description: "Hierarchical location trail.", code: '<Breadcrumb items={items} />' }] }),
  doc({ path: "/components/data/data-table", category: "Data display", group: "Data display", name: "Data Table", description: "Renders consumer-owned rows and column definitions.", module: composites, usage: '<DataTable rows={rows} columns={columns} />', api: [{ name: "rows", type: "T[]", description: "Data supplied by the consumer." }, { name: "columns", type: "DataColumn<T>[]", description: "Column rendering definitions." }, { name: "state", type: "RemoteAsyncState", description: "Loading, error, and empty presentation state." }], variants: [{ name: "Default", description: "Structured data table.", code: '<DataTable rows={rows} columns={columns} />' }, { name: "Loading", description: "Consumer-controlled loading state.", code: '<DataTable state={{ status: "loading" }} />' }, { name: "Empty", description: "Consumer-controlled empty state.", code: '<DataTable state={{ status: "empty" }} />' }] }),
  doc({ path: "/components/data/stat-card", category: "Data display", group: "Data display", name: "Stat Card", description: "Highlights one consumer-provided metric or summary.", module: composites, usage: '<StatCard label="Components" value={42} />', api: [{ name: "label", type: "string", description: "Metric label." }, { name: "value", type: "ReactNode", description: "Consumer-provided value." }, { name: "trend", type: "ReactNode", description: "Optional comparison or context." }], variants: [{ name: "Metric", description: "Single value summary.", code: '<StatCard label="Components" value={42} />' }] }),
  doc({ path: "/components/data/empty-state", category: "Data display", group: "Data display", name: "Empty State", description: "Explains why a surface has no content and provides the next action.", module: composites, usage: '<EmptyState title="No components" action={<Button>Add component</Button>} />', api: [{ name: "title", type: "string", description: "Reason the surface is empty." }, { name: "action", type: "ReactNode", description: "Action that can change the state." }], variants: [{ name: "Actionable", description: "Empty surface with next action.", code: '<EmptyState title="No components" action={...} />' }] }),
  doc({ path: "/components/calendar/date-picker", category: "Calendar & dates", group: "Calendar & dates", name: "Date Picker", description: "Selects one date through a consumer-controlled value.", module: composites, usage: '<DatePicker value={date} onChange={setDate} />', api: [{ name: "value", type: "Date | undefined", description: "Selected date." }, { name: "onChange", type: "(date) => void", description: "Called after selection." }], variants: [{ name: "Single date", description: "One selected date.", code: '<DatePicker value={date} onChange={setDate} />' }] }),
  doc({ path: "/components/calendar/date-range-picker", category: "Calendar & dates", group: "Calendar & dates", name: "Date Range Picker", description: "Selects a start and end date.", module: composites, usage: '<DateRangePicker value={range} onChange={setRange} />', api: [{ name: "value", type: "DateRange", description: "Selected start and end dates." }, { name: "onChange", type: "(range) => void", description: "Called after selection." }], variants: [{ name: "Range", description: "Start and end date selection.", code: '<DateRangePicker value={range} onChange={setRange} />' }] }),
  doc({ path: "/components/calendar/event-calendar", category: "Calendar & dates", group: "Calendar & dates", name: "Event Calendar", description: "Displays consumer-provided events in month, week, or day views.", module: composites, usage: '<EventCalendar events={events} view="month" onEventClick={openEvent} />', api: [{ name: "events", type: "CalendarEvent[]", description: "Events rendered on the calendar." }, { name: "view", type: '"month" | "week" | "day"', description: "Visible calendar view." }, { name: "onEventClick", type: "(event) => void", description: "Consumer action for an event." }], variants: [{ name: "Month", description: "Month grid view.", code: '<EventCalendar view="month" events={events} />' }, { name: "Week", description: "Week schedule view.", code: '<EventCalendar view="week" events={events} />' }, { name: "Day", description: "Single-day schedule view.", code: '<EventCalendar view="day" events={events} />' }] }),
  doc({ path: "/components/charts/chart", category: "Charts & visualization", group: "Charts & visualization", name: "Chart", description: "Renders consumer-provided series as an accessible visualization.", module: composites, usage: '<Chart definition={definition} state={{ status: "ready" }} />', api: [{ name: "definition", type: "ChartDefinition", description: "Series, labels, and chart kind." }, { name: "state", type: "RemoteAsyncState", description: "Loading, error, and empty presentation." }], variants: [{ name: "Line", description: "Trend across ordered values.", code: '<Chart definition={{ kind: "line", ...definition }} />' }, { name: "Area", description: "Trend with filled magnitude.", code: '<Chart definition={{ kind: "area", ...definition }} />' }, { name: "Bar", description: "Compare discrete values.", code: '<Chart definition={{ kind: "bar", ...definition }} />' }, { name: "Pie", description: "Show part-to-whole values.", code: '<Chart definition={{ kind: "pie", ...definition }} />' }, { name: "Donut", description: "Part-to-whole with a center label.", code: '<Chart definition={{ kind: "donut", ...definition }} />' }] }),
  doc({ path: "/components/files/file-uploader", category: "Files & uploads", group: "Files & uploads", name: "File Uploader", description: "Presents selection, validation, progress, and lifecycle states.", module: composites, usage: '<FileUploader files={files} onFilesSelected={addFiles} onUpload={upload} />', api: [{ name: "files", type: "UploadFile[]", description: "Consumer-owned file queue." }, { name: "onFilesSelected", type: "(files) => void", description: "Called after validation." }, { name: "onUpload", type: "UploadAdapter", description: "Consumer-provided upload behavior." }], variants: [{ name: "Dropzone", description: "Drag and drop plus file picker.", code: '<FileUploader onFilesSelected={addFiles} />' }, { name: "Progress", description: "Per-file progress and lifecycle actions.", code: '<FileUploader files={files} onCancel={cancel} onRetry={retry} />' }] }),
  doc({ path: "/components/patterns/command-palette", category: "Patterns", group: "Patterns", name: "Command Palette", description: "Provides searchable application commands through a consumer-owned item list.", module: composites, usage: '<CommandPalette items={items} onSelect={runCommand} />', api: [{ name: "items", type: "CommandItem[]", description: "Commands supplied by the consumer." }, { name: "onSelect", type: "(item) => void", description: "Consumer action for a selected command." }, { name: "shortcut", type: "string", description: "Optional keyboard shortcut label." }], variants: [{ name: "Search", description: "Filtered command list.", code: '<CommandPalette items={items} onSelect={runCommand} />' }] }),
  doc({ path: "/components/patterns/filter-bar", category: "Patterns", group: "Patterns", name: "Filter Bar", description: "Coordinates consumer-owned filters and reset actions.", module: composites, usage: '<FilterBar filters={filters} onChange={setFilters} />', api: [{ name: "filters", type: "FilterDefinition[]", description: "Filter controls and values." }, { name: "onChange", type: "(filters) => void", description: "Called when filters change." }], variants: [{ name: "Default", description: "Inline filter controls.", code: '<FilterBar filters={filters} onChange={setFilters} />' }] }),
];

export const componentGroups = Array.from(new Set(componentRegistry.map((item) => item.group)));
export const componentCounts = { total: componentRegistry.length, core: componentRegistry.filter((item) => item.group === "Core primitives").length, composites: componentRegistry.filter((item) => ["Data display", "Calendar & dates", "Charts & visualization", "Files & uploads", "Patterns"].includes(item.group)).length, shell: componentRegistry.filter((item) => item.module === shell).length };
export function getComponentDoc(path: string) { return componentRegistry.find((item) => item.path === path); }
