import { useRef, useState, type ReactNode } from "react";
import { Button } from "../button/Button";
import { Input } from "../input/Input";
import { cn } from "../../lib/cn";

export function InputGroup({ prefix, suffix, children, className }: { prefix?: ReactNode; suffix?: ReactNode; children: ReactNode; className?: string }) { return <div className={cn("flex items-center rounded-md border border-input bg-background focus-within:ring-2 focus-within:ring-ring/50", className)}>{prefix && <span className="px-3 text-sm text-muted-foreground">{prefix}</span>}{children}{suffix && <span className="px-3 text-sm text-muted-foreground">{suffix}</span>}</div>; }

export function InputOTP({ length = 6, value = "", onChange, className }: { length?: number; value?: string; onChange: (value: string) => void; className?: string }) { const refs = useRef<Array<HTMLInputElement | null>>([]); const chars = Array.from({ length }, (_, index) => value[index] ?? ""); return <div className={cn("flex gap-2", className)}>{chars.map((char, index) => <Input key={index} ref={(element) => { refs.current[index] = element; }} inputMode="numeric" maxLength={1} value={char} aria-label={`Code digit ${index + 1}`} className="size-10 p-0 text-center" onChange={(event) => { const next = event.target.value.replace(/\D/g, "").slice(-1); const updated = chars.map((item, itemIndex) => itemIndex === index ? next : item).join(""); onChange(updated); if (next) refs.current[index + 1]?.focus(); }} onKeyDown={(event) => { if (event.key === "Backspace" && !chars[index]) refs.current[index - 1]?.focus(); }} />)}</div>; }

export function Carousel({ items, renderItem, className }: { items: ReactNode[]; renderItem?: (item: ReactNode, index: number) => ReactNode; className?: string }) { const [index, setIndex] = useState(0); const count = items.length; if (!count) return null; return <div className={cn("grid gap-3", className)}><div className="overflow-hidden rounded-lg border p-4">{renderItem ? renderItem(items[index], index) : items[index]}</div><div className="flex items-center justify-between"><Button size="sm" variant="outline" disabled={count < 2} onClick={() => setIndex((index - 1 + count) % count)}>Previous</Button><span className="text-xs text-muted-foreground">{index + 1} / {count}</span><Button size="sm" variant="outline" disabled={count < 2} onClick={() => setIndex((index + 1) % count)}>Next</Button></div></div>; }

export function Resizable({ children, direction = "horizontal", defaultSize = 50, min = 20, max = 80, className }: { children: [ReactNode, ReactNode]; direction?: "horizontal" | "vertical"; defaultSize?: number; min?: number; max?: number; className?: string }) { const [size, setSize] = useState(defaultSize); const firstStyle = direction === "horizontal" ? { width: `${size}%` } : { height: `${size}%` }; const secondStyle = direction === "horizontal" ? { width: `${100 - size}%` } : { height: `${100 - size}%` }; return <div className={cn("flex min-h-32", direction === "vertical" && "flex-col", className)}><div style={firstStyle} className="min-w-0 overflow-auto">{children[0]}</div><input aria-label="Resize panels" type="range" min={min} max={max} value={size} onChange={(event) => setSize(Number(event.target.value))} className={cn(direction === "horizontal" ? "w-2" : "h-2 w-full", "shrink-0 accent-primary")} /><div style={secondStyle} className="min-w-0 overflow-auto">{children[1]}</div></div>; }
