import { useMemo } from "react";
import { Button } from "../../core/button/Button";
import type { EventCalendarContract } from "../../contracts/calendar";
import { addDays, isSameDay, monthDays, startOfWeek } from "./calendar-utils";

const labels = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

export function EventCalendar({ events, view, date, onDateChange, onViewChange, onEventClick, onSlotClick }: EventCalendarContract) {
  const days = useMemo(() => view === "month" ? monthDays(date) : Array.from({ length: view === "week" ? 7 : 1 }, (_, index) => addDays(startOfWeek(date), index)), [date, view]);
  const title = view === "month" ? date.toLocaleDateString(undefined, { month: "long", year: "numeric" }) : view === "week" ? `Week of ${startOfWeek(date).toLocaleDateString()}` : date.toLocaleDateString();
  const shiftDate = (amount: number) => { const next = new Date(date); if (view === "month") next.setMonth(next.getMonth() + amount); else next.setDate(next.getDate() + amount * (view === "week" ? 7 : 1)); onDateChange(next); };
  const handleKeyDown = (event: React.KeyboardEvent<HTMLElement>) => { const amount = event.key === "ArrowLeft" ? -1 : event.key === "ArrowRight" ? 1 : event.key === "ArrowUp" ? -7 : event.key === "ArrowDown" ? 7 : 0; if (amount) { event.preventDefault(); onDateChange(addDays(date, amount)); } };
  return <section aria-label="Event calendar" className="grid gap-4 rounded-lg border p-4" onKeyDown={handleKeyDown} tabIndex={0}><header className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">{title}</h2><p className="text-sm text-muted-foreground">Pilih tanggal untuk melihat event.</p></div><div className="flex items-center gap-2"><Button size="sm" variant="outline" onClick={() => shiftDate(-1)}>Previous</Button><Button size="sm" variant="outline" onClick={() => onDateChange(new Date())}>Today</Button><Button size="sm" variant="outline" onClick={() => shiftDate(1)}>Next</Button><select aria-label="Calendar view" value={view} onChange={(event) => onViewChange(event.target.value as EventCalendarContract["view"])} className="h-8 rounded-md border border-input bg-background px-2 text-sm"><option value="month">Month</option><option value="week">Week</option><option value="day">Day</option></select></div></header><div className={view === "month" ? "grid grid-cols-7 gap-px overflow-hidden rounded-md border bg-border" : "grid gap-px overflow-hidden rounded-md border bg-border"} style={view === "week" ? { gridTemplateColumns: "repeat(7, minmax(0, 1fr))" } : undefined}>{view === "month" && labels.map((label) => <div className="bg-muted p-2 text-center text-xs font-medium text-muted-foreground" key={label}>{label}</div>)}{days.map((day) => { const dayEvents = events.filter((event) => isSameDay(event.start, day)); return <div key={day.toISOString()} className={`min-h-24 bg-background p-2 text-left align-top ${isSameDay(day, date) ? "ring-2 ring-inset ring-primary" : ""}`}><button type="button" onClick={() => onSlotClick?.(day)} className="block min-h-8 w-full text-left hover:bg-muted/50"><span className="text-xs font-medium">{view === "month" ? day.getDate() : day.toLocaleDateString(undefined, { weekday: "short", day: "numeric" })}</span></button><span className="mt-2 grid gap-1">{dayEvents.map((event) => <button type="button" key={event.id} className="truncate rounded bg-muted px-1.5 py-1 text-left text-xs hover:bg-accent" onClick={() => onEventClick?.(event)}>{event.title}</button>)}{dayEvents.length === 0 && view === "day" && <span className="text-xs text-muted-foreground">No events</span>}</span></div>; })}</div></section>;
}
