import { cloneElement, isValidElement, useId, useState, type ReactElement, type ReactNode } from "react";
import { cn } from "../../lib/cn";

export function DropdownMenu({ trigger, children }: { trigger: ReactNode; children: ReactNode }) {
  const [open, setOpen] = useState(false);
  const menuId = useId();
  const triggerElement = isValidElement(trigger)
    ? cloneElement(trigger as ReactElement<{ onClick?: () => void; "aria-expanded"?: boolean; "aria-controls"?: string }>, { onClick: () => setOpen((value) => !value), "aria-expanded": open, "aria-controls": menuId })
    : <button type="button" aria-expanded={open} aria-controls={menuId} onClick={() => setOpen((value) => !value)}>{trigger}</button>;
  return <span className="relative inline-flex">{triggerElement}{open && <div id={menuId} role="menu" className="absolute right-0 top-full z-40 mt-2 min-w-44 rounded-md border bg-popover p-1 text-popover-foreground shadow-md">{children}</div>}</span>;
}
export function DropdownMenuItem({ children, onSelect, disabled = false }: { children: ReactNode; onSelect?: () => void; disabled?: boolean }) { return <button type="button" role="menuitem" disabled={disabled} className="flex w-full items-center rounded-sm px-2 py-1.5 text-left text-sm hover:bg-muted disabled:pointer-events-none disabled:opacity-50" onClick={onSelect}>{children}</button>; }
export function DropdownMenuSeparator() { return <div role="separator" className="-mx-1 my-1 h-px bg-border" />; }

export function ContextMenu({ children, menu }: { children: ReactNode; menu: ReactNode }) { const [open, setOpen] = useState(false); return <span className="relative inline-flex" onContextMenu={(event) => { event.preventDefault(); setOpen(true); }} onClick={() => setOpen(false)}>{children}{open && <div role="menu" className="absolute left-0 top-full z-40 mt-1 min-w-44 rounded-md border bg-popover p-1 shadow-md">{menu}</div>}</span>; }
export function Menubar({ children, className }: { children: ReactNode; className?: string }) { return <nav role="menubar" className={cn("flex items-center gap-1 rounded-lg border bg-background p-1", className)}>{children}</nav>; }
export function MenubarItem({ children, href, onClick }: { children: ReactNode; href?: string; onClick?: () => void }) { return href ? <a role="menuitem" className="rounded-md px-3 py-1.5 text-sm hover:bg-muted" href={href}>{children}</a> : <button type="button" role="menuitem" className="rounded-md px-3 py-1.5 text-sm hover:bg-muted" onClick={onClick}>{children}</button>; }
export function NavigationMenu({ children, className }: { children: ReactNode; className?: string }) { return <nav aria-label="Navigation" className={cn("flex items-center gap-1", className)}>{children}</nav>; }
export function NavigationMenuLink({ children, href, active = false }: { children: ReactNode; href: string; active?: boolean }) { return <a href={href} aria-current={active ? "page" : undefined} className={cn("rounded-md px-3 py-2 text-sm hover:bg-muted", active && "bg-muted font-medium")}>{children}</a>; }
export function Combobox({ options, value, onValueChange, placeholder = "Select..." }: { options: { value: string; label: string }[]; value?: string; onValueChange: (value: string) => void; placeholder?: string }) { const [query, setQuery] = useState(""); const [open, setOpen] = useState(false); const selected = options.find((option) => option.value === value); const visible = options.filter((option) => option.label.toLowerCase().includes(query.toLowerCase())); return <span className="relative block"><input role="combobox" aria-expanded={open} value={selected?.label ?? query} placeholder={placeholder} onFocus={() => setOpen(true)} onChange={(event) => { setQuery(event.target.value); setOpen(true); }} className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring/50" />{open && <div role="listbox" className="absolute top-full z-40 mt-1 max-h-48 w-full overflow-auto rounded-md border bg-popover p-1 shadow-md">{visible.map((option) => <button type="button" role="option" aria-selected={option.value === value} key={option.value} className="block w-full rounded px-2 py-1.5 text-left text-sm hover:bg-muted" onClick={() => { onValueChange(option.value); setQuery(""); setOpen(false); }}>{option.label}</button>)}</div>}</span>; }
